export const SAMPLE_PROJECTS = [
  {
    projectId: 'PROJ001',
    projectName: 'E-Commerce Platform',
    category: 'Major',
    domain: 'Web Development',
    technologyStack: ['MongoDB', 'Express', 'React', 'Node.js', 'Stripe'],
    branch: 'CSE',
    difficultyLevel: 'Advanced',
    description: 'A complete e-commerce platform with product catalog, shopping cart, and payment integration',
    longDescription:
      'Build a full-featured e-commerce platform with advanced features including product catalog, user authentication, shopping cart functionality, and secure payment processing using Stripe. Includes admin dashboard for managing products and orders.',
  },
  {
    projectId: 'PROJ002',
    projectName: 'Real-Time Chat Application',
    category: 'Major',
    domain: 'Web Development',
    technologyStack: ['React', 'Node.js', 'Socket.io', 'MongoDB'],
    branch: 'CSE',
    difficultyLevel: 'Intermediate',
    description: 'A real-time chat application with user authentication and message history',
    longDescription:
      'Develop a real-time chat application allowing users to communicate instantly. Features include user authentication, one-to-one and group chat functionality, message persistence, and typing indicators.',
  },
  {
    projectId: 'PROJ003',
    projectName: 'Machine Learning Image Classification',
    category: 'Major',
    domain: 'Machine Learning',
    technologyStack: ['Python', 'TensorFlow', 'Keras', 'NumPy', 'Pandas'],
    branch: 'CSE',
    difficultyLevel: 'Advanced',
    description: 'An ML model for classifying images using deep learning',
    longDescription:
      'Create a deep learning model using TensorFlow and Keras to classify images from the CIFAR-10 dataset. Includes data preprocessing, model training, evaluation, and web API for predictions.',
  },
  {
    projectId: 'PROJ004',
    projectName: 'Weather Monitoring IoT System',
    category: 'Major',
    domain: 'IoT',
    technologyStack: ['Arduino', 'Python', 'Flask', 'MongoDB'],
    branch: 'ECE',
    difficultyLevel: 'Intermediate',
    description: 'An IoT system for real-time weather monitoring and data collection',
    longDescription:
      'Build an IoT system using Arduino sensors to monitor temperature, humidity, and air quality. Data is sent to a cloud server and displayed on a web dashboard with analytics.',
  },
  {
    projectId: 'PROJ005',
    projectName: 'Task Management App',
    category: 'Mini',
    domain: 'Web Development',
    technologyStack: ['React', 'Firebase', 'Tailwind CSS'],
    branch: 'CSE',
    difficultyLevel: 'Beginner',
    description: 'A simple task management application with CRUD operations',
    longDescription:
      'Create a web-based task management application where users can create, update, delete, and track their tasks. Features include task categorization, due dates, and priority levels.',
  },
  {
    projectId: 'PROJ006',
    projectName: 'Blog Platform',
    category: 'Mini',
    domain: 'Web Development',
    technologyStack: ['Next.js', 'MongoDB', 'Tailwind CSS'],
    branch: 'CSE',
    difficultyLevel: 'Intermediate',
    description: 'A blogging platform with markdown support and commenting',
    longDescription:
      'Build a blogging platform with features like markdown editor, comment system, tagging, and SEO optimization. Includes user authentication and admin panel for content management.',
  },
  {
    projectId: 'PROJ007',
    projectName: 'Python Web Scraper',
    category: 'Mini',
    domain: 'Python Development',
    technologyStack: ['Python', 'BeautifulSoup', 'Selenium'],
    branch: 'CSE',
    difficultyLevel: 'Beginner',
    description: 'A web scraping tool for collecting data from websites',
    longDescription:
      'Develop a web scraper using Python to extract and organize data from websites. Includes data cleaning, storage in databases, and export functionality.',
  },
  {
    projectId: 'PROJ008',
    projectName: 'Android Weather App',
    category: 'Mini',
    domain: 'Mobile Development',
    technologyStack: ['Java', 'Android SDK', 'REST API'],
    branch: 'CSE',
    difficultyLevel: 'Intermediate',
    description: 'A mobile application for weather forecasting and alerts',
    longDescription:
      'Create an Android app that displays real-time weather data using weather APIs. Features include location-based forecasts, weather alerts, and historical data visualization.',
  },
  {
    projectId: 'PROJ009',
    projectName: 'Movie Recommendation System',
    category: 'Major',
    domain: 'Machine Learning',
    technologyStack: ['Python', 'Scikit-learn', 'Flask', 'Pandas'],
    branch: 'CSE',
    difficultyLevel: 'Advanced',
    description: 'An ML-based movie recommendation engine using collaborative filtering',
    longDescription:
      'Build a movie recommendation system using collaborative filtering algorithms. Includes user profiling, matrix factorization, and a web interface to get recommendations.',
  },
  {
    projectId: 'PROJ010',
    projectName: 'Attendance Management System',
    category: 'Mini',
    domain: 'Web Development',
    technologyStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'MySQL'],
    branch: 'CSE',
    difficultyLevel: 'Beginner',
    description: 'A simple attendance tracking system for educational institutions',
    longDescription:
      'Create a web-based attendance system for managing student attendance records. Includes features for roll call, reports, and notifications to parents.',
  },
];
